In [ ]:
# emigrate.bin

In [11]:
22704 / 8 / 33

86.0

In [2]:
import pandas as pd

In [2]:
popu = pd.read_csv("data/population.csv")

In [6]:
popu.loc[:,"race"]

0          chinese
1          chinese
2          chinese
3          chinese
4          chinese
            ...   
2705110      malay
2705111     indian
2705112     indian
2705113     indian
2705114      other
Name: race, Length: 2705115, dtype: object

In [3]:
popu

year_of_birth     race  gender
0                 1990  chinese    male
1                 1990  chinese    male
2                 1990  chinese    male
3                 1990  chinese    male
4                 1990  chinese    male
...                ...      ...     ...
2705110           1890    malay  female
2705111           1890   indian    male
2705112           1890   indian    male
2705113           1890   indian  female
2705114           1890    other  female

[2705115 rows x 3 columns]

In [217]:
popu2 = pd.read_csv("data/M810801.csv", index_col=0, header=0, engine='python' )

In [218]:
popu2.head()

2024     2023     2022     2021     2020     2019  \
Data Series                                                                
Total Male Chinese  1497655  1489028  1466366  1440854  1461344  1455708   
  0 Year               9652     9886    10472    10530    11176    11072   
  1 Year              10620    11210    11289    12116    11950    11973   
  2 Year              11460    11616    12529    12086    12254    12884   
  3 Year              11786    12823    12506    12287    13055    13849   

                       2018     2017     2016     2015  ...     1999     1998  \
Data Series                                             ...                     
Total Male Chinese  1445375  1436284  1425244  1415303  ...  1235326  1219890   
  0 Year              10995    11498    12152    12343  ...    14684    16204   
  1 Year              12506    13238    13395    12650  ...    16556    16975   
  2 Year              13609    13860    12951    14099  ...    17168    17558   
  3 Year              14112    13209    14343    13892  ...    17711    18095   

                       1997     1996     1995     1994     1993     1992  \
Data Series                                                                
Total Male Chinese  1202346  1184861  1166321  1148073  1130006  1111147   
  0 Year              16663    17080    17509    17644    17702    17102   
  1 Year              17349    17793    17953    17957    17360    18539   
  2 Year              17947    18132    18114    17516    18700    17176   
  3 Year              18274    18280    17648    18817    17341    19597   

                       1991     1990  
Data Series                           
Total Male Chinese  1092546  1071055  
  0 Year              18396    16814  
  1 Year              17002    19236  
  2 Year              19429    17155  
  3 Year              17325    13963  

[5 rows x 35 columns]

In [136]:
popu2.iloc[174:261,]

2024    2023    2022    2021    2020    2019    2018  \
Data Series                                                                 
Total Male Malays  280817  279017  275876  271743  271332  268933  266486   
  0 Year             3705    3996    4246    3976    4113    3884    3999   
  1 Year             4033    4299    4042    4197    3960    4102    3873   
  2 Year             4303    4053    4228    3943    4106    3885    3763   
  3 Year             4055    4240    3970    4101    3890    3778    3523   
...                   ...     ...     ...     ...     ...     ...     ...   
  81 Year             434     380     475     503     522     471     423   
  82 Year             343     441     468     477     432     388     393   
  83 Year             399     425     434     392     360     351     439   
  84 Year             378     381     346     317     320     390     344   
  85 Years & Over    1733    1637    1605    1601    1579    1456    1366   

                     2017    2016    2015  ...    1999    1998    1997  \
Data Series                                ...                           
Total Male Malays  263912  261564  259108  ...  226306  223404  220418   
  0 Year             3790    3672    3423  ...    4431    4445    4552   
  1 Year             3760    3509    3441  ...    4453    4570    4672   
  2 Year             3517    3453    3226  ...    4582    4676    4756   
  3 Year             3469    3248    3099  ...    4678    4763    5096   
...                   ...     ...     ...  ...     ...     ...     ...   
  81 Year             418     536     448  ...     259     226     148   
  82 Year             488     410     363  ...     196     129     113   
  83 Year             375     334     285  ...     113      99      87   
  84 Year             290     256     235  ...      87      78     133   
  85 Years & Over    1323    1316    1303  ...     465     487     456   

                     1996    1995    1994    1993    1992    1991    1990  
Data Series                                                                
Total Male Malays  217366  214148  210859  207140  203455  199840  195950  
  0 Year             4666    4736    5070    5040    4947    5194    5056  
  1 Year             4752    5079    5051    4942    5203    5056    4921  
  2 Year             5089    5060    4941    5209    5054    4913    4671  
  3 Year             5069    4942    5218    5052    4904    4658    4198  
...                   ...     ...     ...     ...     ...     ...     ...  
  81 Year             131     112     195     223     130     147     118  
  82 Year              95     174     198     119     129     105     139  
  83 Year             154     179     104     117      87     123      86  
  84 Year             155      88     101      73     111      74      56  
  85 Years & Over     379     364     343     341     298     265     254  

[87 rows x 35 columns]

In [ ]:
pairs = [ (1,87), (88,174),(175,262),]

In [54]:
import numpy as np
import pandas as pd

# Define the dimensions of the matrix
result_matrix = np.zeros((8, 86, 35))

# Simulating popu2 for demonstration (you can replace this with your actual data)

# Initialize and fill the result_matrix
start = 1
for n in range(8):
    end = start + 86
    result_matrix[n, :, :] = popu2.iloc[start:end, :].to_numpy()[:, ::-1]  # Reversing columns 0 to 34
    start = end +1

# Save the result_matrix to a file (in binary format)


In [135]:
result_matrix

array([[[1.6814e+04, 1.8396e+04, 1.7102e+04, ..., 1.0472e+04,
         9.8860e+03, 9.6520e+03],
        [1.9236e+04, 1.7002e+04, 1.8539e+04, ..., 1.1289e+04,
         1.1210e+04, 1.0620e+04],
        [1.7155e+04, 1.9429e+04, 1.7176e+04, ..., 1.2529e+04,
         1.1616e+04, 1.1460e+04],
        ...,
        [9.8800e+02, 1.0820e+03, 1.0780e+03, ..., 5.1730e+03,
         5.4010e+03, 5.6550e+03],
        [7.4600e+02, 8.7500e+02, 9.6700e+02, ..., 4.0250e+03,
         4.8150e+03, 5.0550e+03],
        [2.7360e+03, 2.9930e+03, 3.3060e+03, ..., 1.7685e+04,
         1.8905e+04, 2.0867e+04]],

       [[1.5339e+04, 1.7017e+04, 1.6210e+04, ..., 9.8980e+03,
         9.1860e+03, 9.2040e+03],
        [1.8065e+04, 1.5535e+04, 1.7232e+04, ..., 1.0714e+04,
         1.0724e+04, 9.9170e+03],
        [1.5941e+04, 1.8236e+04, 1.5688e+04, ..., 1.2118e+04,
         1.1031e+04, 1.0975e+04],
        ...,
        [1.6670e+03, 1.7720e+03, 1.8150e+03, ..., 7.6120e+03,
         7.8620e+03, 8.1160e+03],
        [1.3

In [55]:
np.save('result_matrix.npy', result_matrix)

In [56]:
result_matrix_load = np.load('result_matrix.npy')

In [61]:
result_matrix.tofile('result_matrix_data.bin')

array([[16814., 18396., 17102., ..., 10472.,  9886.,  9652.],
       [19236., 17002., 18539., ..., 11289., 11210., 10620.],
       [17155., 19429., 17176., ..., 12529., 11616., 11460.],
       ...,
       [  988.,  1082.,  1078., ...,  5173.,  5401.,  5655.],
       [  746.,   875.,   967., ...,  4025.,  4815.,  5055.],
       [ 2736.,  2993.,  3306., ..., 17685., 18905., 20867.]])

In [3]:
death_data = pd.read_csv("data/death_sg.csv", index_col=0, header=0, engine='python')

In [4]:
# Iterate from the second right-most column to the left
for col in reversed(range(len(death_data.columns) - 1)):
    current_col = death_data.columns[col]
    next_col = death_data.columns[col + 1]
    # use mask
    mask = death_data[current_col] == '-'
    death_data.loc[mask, current_col] = death_data.loc[mask, next_col]

print(death_data)

                                 2023   2022   2021   2020   2019   2018  \
Data Series                                                                
Male Age Specific Death Rate      6.9    6.9    6.5    5.9    5.6    5.6   
  Under 1 Year                    1.9    1.9    1.6    2.1    1.8    2.3   
  1 - 4 Years                     0.2    0.2    0.1    0.1    0.1    0.1   
  5 - 9 Years                     0.1    0.1    0.1    0.1    0.1    0.1   
  10 - 14 Years                   0.2    0.2    0.1    0.1    0.1    0.1   
  15 - 19 Years                   0.3    0.2    0.3    0.2    0.2    0.3   
  20 - 24 Years                   0.4    0.4    0.3    0.3    0.4    0.4   
  25 - 29 Years                   0.5    0.5    0.4    0.3    0.3    0.3   
  30 - 34 Years                   0.5    0.5    0.4    0.4    0.4    0.5   
  35 - 39 Years                   0.6    0.6    0.7    0.6    0.6    0.6   
  40 - 44 Years                   1.0    1.1      1      1      1    0.9   
  45 - 49 Ye

/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_17845/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]
/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_17845/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]
/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_17845/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, pleas

In [6]:
import numpy as np
# Define the dimensions of the matrix
mortality_matrix = np.zeros((2, 19, 34))

# Simulating popu2 for demonstration (you can replace this with your actual data)

# Initialize and fill the result_matrix
start = 1
for n in range(2):
    end = start + 19
    mortality_matrix[n, :, :] = death_data.iloc[start:end, :].to_numpy()[:, ::-1]  # Reversing columns 0 to 34
    start = end +1 


In [7]:
death_data.iloc[1:20,:]

2023   2022   2021   2020   2019   2018   2017   2016  \
Data Series                                                               
Under 1 Year       1.9    1.9    1.6    2.1    1.8    2.3      2    2.3   
1 - 4 Years        0.2    0.2    0.1    0.1    0.1    0.1    0.1    0.2   
5 - 9 Years        0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1   
10 - 14 Years      0.2    0.2    0.1    0.1    0.1    0.1    0.1    0.2   
15 - 19 Years      0.3    0.2    0.3    0.2    0.2    0.3    0.3    0.3   
20 - 24 Years      0.4    0.4    0.3    0.3    0.4    0.4    0.3    0.3   
25 - 29 Years      0.5    0.5    0.4    0.3    0.3    0.3    0.3    0.4   
30 - 34 Years      0.5    0.5    0.4    0.4    0.4    0.5    0.5    0.4   
35 - 39 Years      0.6    0.6    0.7    0.6    0.6    0.6    0.7    0.6   
40 - 44 Years      1.0    1.1      1      1      1    0.9    1.1    1.1   
45 - 49 Years      1.7    1.8    1.9    1.6    1.7    1.8    1.7    1.7   
50 - 54 Years      2.8    3.0    2.9    2.8    2.6    2.8    3.1    3.1   
55 - 59 Years      4.9    4.6    5.1    4.7    4.5      5    4.8    5.3   
60 - 64 Years      8.1    8.1    8.6    7.9    7.7    8.2    8.2    8.2   
65 - 69 Years     13.5   13.2   12.6     12   11.9   12.5   12.9   13.3   
70 - 74 Years     20.3   21.6   21.4   20.5   20.2   22.4   22.9   22.5   
75 - 79 Years     35.6   36.9     36   35.5   35.3   35.9   37.4   38.4   
80 - 84 Years     66.7   69.2   63.7     64   63.5   62.8   65.5   66.6   
85 Years & Over  137.1  152.8  140.5  123.3  122.2  123.4  128.9  124.2   

                  2015   2014  ...   1999   1998   1997   1996   1995   1994  \
Data Series                    ...                                             
Under 1 Year       2.2    1.9  ...    3.2    4.1    4.0    3.5    4.3    4.3   
1 - 4 Years        0.2    0.1  ...    0.2    0.3    0.3    0.4    0.4    0.4   
5 - 9 Years        0.1    0.1  ...    0.1    0.1    0.2    0.2    0.2    0.2   
10 - 14 Years      0.1    0.1  ...    0.2    0.2    0.2    0.3    0.3    0.3   
15 - 19 Years      0.2    0.3  ...    0.4    0.4    0.4    0.5    0.5    0.5   
20 - 24 Years      0.3    0.4  ...    0.7    0.6    0.8    0.7    0.7    0.7   
25 - 29 Years      0.4    0.3  ...    0.6    0.6    0.6    0.7    0.6    0.7   
30 - 34 Years      0.5    0.5  ...    0.7    0.8    0.8    0.8    0.8    0.8   
35 - 39 Years      0.7    0.7  ...    1.0    1.1    1.0    1.2    1.3    1.3   
40 - 44 Years      1.1    1.3  ...    1.7    1.7    1.9    2.0    1.8    2.0   
45 - 49 Years      1.9    1.7  ...    2.5    2.8    2.6    3.1    3.6    3.2   
50 - 54 Years      3.1      3  ...    4.7    4.9    5.3    5.9    5.8    6.0   
55 - 59 Years      5.4    5.8  ...    8.3    9.1    9.2    9.7   10.7   10.5   
60 - 64 Years      8.5    8.4  ...   16.0   16.2   16.7   17.9   18.0   17.9   
65 - 69 Years     13.9   13.8  ...   25.1   27.4   27.0   28.1   29.6   30.7   
70 - 74 Years     23.9   24.4  ...   37.8   41.8   40.9   43.1   46.6   45.4   
75 - 79 Years       41     41  ...   64.2   64.9   67.4   71.1   74.2   70.0   
80 - 84 Years     63.7   70.6  ...   96.2  103.4   97.8  104.0  105.2  100.6   
85 Years & Over  124.8  128.5  ...  150.5  135.2  131.6  141.0  151.4  139.6   

                  1993   1992   1991   1990  
Data Series                                  
Under 1 Year       5.0    5.2    5.8    7.1  
1 - 4 Years        0.3    0.3    0.3    0.4  
5 - 9 Years        0.1    0.3    0.2    0.2  
10 - 14 Years      0.3    0.4    0.2    0.3  
15 - 19 Years      0.5    0.5    0.5    0.5  
20 - 24 Years      0.8    0.8    0.7    0.8  
25 - 29 Years      0.6    0.8    0.8    0.8  
30 - 34 Years      0.7    0.9    0.9    0.9  
35 - 39 Years      1.0    1.2    1.2    1.4  
40 - 44 Years      2.0    2.1    1.9    2.1  
45 - 49 Years      3.4    3.7    3.4    4.0  
50 - 54 Years      6.1    6.1    6.7    6.8  
55 - 59 Years     10.5   10.9   12.5   12.0  
60 - 64 Years     18.4   20.3   20.6   20.8  
65 - 69 Years     29.2   

In [86]:
mortality_matrix[0,18,:]

array([142.3, 135.1, 147.1, 137.5, 139.6, 151.4, 141. , 131.6, 135.2,
       150.5, 147.7, 143.5, 142.5, 150.1, 146.5, 142.3, 141.9, 145.3,
       135.8, 135.6, 140. , 130.8, 132.3, 131. , 128.5, 124.8, 124.2,
       128.9, 123.4, 122.2, 123.3, 140.5, 152.8, 137.1])

In [ ]:
# for i in range(2):
#     death_by_year = mortality_matrix[i,:,:]
#     initialize a death_by_cohort matrix with 0 
    
#     death_by_year, except 1st and last row, expand every row 4 times , get  full_death_table
    
#     for ith row, the row should be from (i,0) till (i+33,33) of full_death_table; if the index it outside the matrix
#     for the rest of the row, replace it with the last avaliable in the loop.  
    
    
    
# death for people 
# death for people after 1990, or 1990 -2 years old 
   

In [28]:
import numpy as np
# 1991 - 2023 
emi_rate = np.fromfile("data/bin/emigrate.bin")
emi_rate = emi_rate.reshape(8, 86, 33)

In [29]:
emi_rate[0,:,:]

array([[ 0.        ,  0.        ,  0.        , ..., -0.01098901,
         0.        , -0.07650631],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        , -0.02355072,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.0089404 , -0.01165919,  0.        , ..., -0.00312953,
         0.        ,  0.        ]])

In [8]:
import numpy as np

# Assuming mortality_matrix is already defined
death_by_cohort = np.zeros((2,86, 34))  # male, female; 0 - 85, 85+; for 1990 - 2023

for i in range(2):
    death_by_year = mortality_matrix[i, :, :]
    # Expand every row 5 times to get mortality rate from 0 - 85+
    death_table_4 = np.repeat(death_by_year[1:2], 4, axis=0)
    full_death_table = np.repeat(death_by_year[2:-1], 5, axis=0)
    full_death_table = np.vstack((death_by_year[0],death_table_4, full_death_table, death_by_year[-1]))

    #... 
    full_death_df = pd.DataFrame(full_death_table)

    # Save the DataFrame to a CSV file
    full_death_df.to_csv(f"useless/death_{i}.csv", index=False)
    # Iterate through each row and generate the death_by_cohort
    for j in range(86):
        # modify and check boundary
        # initialize vec with 0 
        vec = np.zeros(34)
        # for the upper matrix 
        for k in range(34):
                row_idx = min(85, j+k)
                vec[k] = full_death_table[row_idx, k]
            # diagnosis first, and then horizontal
        death_by_cohort[i, j, :] = vec
        # Fill the rest of the row with the last available value
        


In [ ]:
death_by_cohort[0,:,:] # male 



In [ ]:
death_data.iloc[1:20, ::-1]

In [ ]:
death_data.iloc[21:40, ::-1]

In [ ]:
death_data.iloc[1:20,:]

In [144]:
death_by_cohort.tofile('data/bin/death_by_cohort.bin')

### death for migration



In [16]:
import numpy as np

def extract_padded_diagonals(full_death_table):
    nrows, ncols = full_death_table.shape
    max_len = ncols

    # To store diagonals, padded to length 4
    diagonals = []

    # Extract the diagonals and pad them with zeros
    for start_col in range(ncols):
        diag = []
        row, col = 0, start_col

        # Collect the diagonal elements starting from (0, start_col)
        while row < nrows and col < ncols:
            diag.append(full_death_table[row, col])
            row += 1
            col += 1

        # Pad with zeros if the length is less than 4
        while len(diag) < max_len:
            diag.insert(0, 0)

        diagonals.append(diag)

    # Skip the first diagonal and convert the rest to a matrix
    matrix_rows = []
    for diag in diagonals[1:]:  # Start from the second diagonal
        # Exclude the first value (which is padding, i.e., 0)
        matrix_rows.append(diag)

    # Create a NumPy matrix from the rows
    result_matrix = np.array(matrix_rows)

    return result_matrix

# Example usage
full_death_table = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5, 1.6],
    [1.7, 1.8, 1.9, 2.0]
])

result = extract_padded_diagonals(full_death_table)
print(result)


[[0.  0.2 0.7 1.2]
 [0.  0.  0.3 0.8]
 [0.  0.  0.  0.4]]


In [31]:
full_death_table.shape

(86, 34)

In [ ]:
# for i in range(emi_rate.shape[0]):
#     zero_column = np.zeros((emi_rate.shape[1], 1))
#     emi_rate[i] = np.concatenate((zero_column,emi_rate[i] ), axis=1)

# print(emi_rate.shape)
# could not do it

In [42]:
# Create a new array with an additional column (shape becomes (8, 86, 34))
emi_rate_new = np.zeros((8, 86, 34))

# Copy the existing data from emi_rate to emi_rate_new
emi_rate_new[:, :, 1:] = emi_rate

In [43]:
emi_rate_new[0,:,:]

array([[ 0.        ,  0.        ,  0.        , ..., -0.01098901,
         0.        , -0.07650631],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        , -0.02355072, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , -0.0089404 , -0.01165919, ..., -0.00312953,
         0.        ,  0.        ]])

In [51]:
full_death_table / 1000

array([[6.20000000e-03, 4.80000000e-03, 4.40000000e-03, ...,
        1.46548857e-03, 1.08574238e-03, 2.00186916e-03],
       [2.00000000e-04, 3.00000000e-04, 3.00000000e-04, ...,
        1.00000000e-04, 1.00000000e-04, 1.00000000e-04],
       [2.00000000e-04, 3.00000000e-04, 3.00000000e-04, ...,
        1.00000000e-04, 1.00000000e-04, 1.00000000e-04],
       ...,
       [7.86000000e-02, 7.10000000e-02, 7.29000000e-02, ...,
        3.97000000e-02, 4.36000000e-02, 4.10000000e-02],
       [7.86000000e-02, 7.10000000e-02, 7.29000000e-02, ...,
        3.97000000e-02, 4.36000000e-02, 4.10000000e-02],
       [1.29400000e-01, 1.25200000e-01, 1.27000000e-01, ...,
        1.09100000e-01, 1.22000000e-01, 1.20600000e-01]])

In [73]:

# for the new birth before 

ncols = 34
nrows = 2023 - 1991 + 1
death_mig_cohort = np.zeros((8,nrows, 34))
death_by_cohort = np.zeros((8,86, 34))  

for i in range(1):
    death_by_year = mortality_matrix[i % 2, :, :]
    # Expand every row 5 times to get mortality rate from 0 - 85+
    death_table_4 = np.repeat(death_by_year[1:2], 4, axis=0)
    full_death_table = np.repeat(death_by_year[2:-1], 5, axis=0)
    full_death_table = np.vstack((death_by_year[0],death_table_4, full_death_table, death_by_year[-1]))

    # emi_rate_new is negative
    full_disappear_table = full_death_table / 1000 - emi_rate_new[i,:,:]
    #... 
    #full_death_df = pd.DataFrame(full_death_table)
    
    # migration 
    death_mig_cohort[i,:,:] = extract_padded_diagonals(full_disappear_table)
    
    # born 1990 
    for j in range(86):
        # modify and check boundary
        # initialize vec with 0 
        vec = np.zeros(34)
        # for the upper matrix 
        for k in range(34):
                row_idx = min(85, j+k)
                vec[k] = full_disappear_table[row_idx, k]
            # diagnosis first, and then horizontal
        death_by_cohort[i, j, :] = vec
            
        
    

In [75]:
combined_death_cohort = np.concatenate(
    (death_mig_cohort,death_by_cohort),
    axis=1)


In [78]:
death_by_cohort.shape

(8, 86, 34)

In [82]:
death_by_cohort[0,1,:]

array([0.0004    , 0.0003    , 0.0003    , 0.0003    , 0.0002    ,
       0.0002    , 0.0002    , 0.0002    , 0.0001    , 0.0002    ,
       0.0003    , 0.0001    , 0.0001    , 0.00230475, 0.0003    ,
       0.00196757, 0.00157639, 0.0002    , 0.0003    , 0.0005    ,
       0.0004    , 0.0005    , 0.0005    , 0.0004    , 0.0003    ,
       0.0004    , 0.0004    , 0.0003    , 0.0003    , 0.0004    ,
       0.0004    , 0.0025575 , 0.0005    , 0.0005    ])

In [77]:
combined_death_cohort.shape

(8, 119, 34)

In [79]:
combined_death_cohort.tofile("data/bin/disappear.bin")

In [80]:
death_by_cohort.tofile("data/bin/mig_disappear.bin")

In [ ]:
+39  # uniform... 

In [74]:
death_by_cohort

array([[[0.0071    , 0.0003    , 0.0003    , ..., 0.0004    ,
         0.0005    , 0.0005    ],
        [0.0004    , 0.0003    , 0.0003    , ..., 0.0025575 ,
         0.0005    , 0.0005    ],
        [0.0004    , 0.0003    , 0.0003    , ..., 0.00495809,
         0.0005    , 0.0006    ],
        ...,
        [0.0972    , 0.1031    , 0.15875919, ..., 0.14362953,
         0.1528    , 0.1371    ],
        [0.0972    , 0.1440404 , 0.15875919, ..., 0.14362953,
         0.1528    , 0.1371    ],
        [0.1423    , 0.1440404 , 0.15875919, ..., 0.14362953,
         0.1528    , 0.1371    ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 

In [72]:
death_mig_cohort[0,32,:]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07840631])

In [71]:
full_disappear_table[0,:]

array([0.0071    , 0.0058    , 0.0052    , 0.005     , 0.0043    ,
       0.0043    , 0.0035    , 0.004     , 0.0041    , 0.0032    ,
       0.05986107, 0.0024    , 0.0034    , 0.0028    , 0.0022    ,
       0.0024    , 0.0028    , 0.0026    , 0.0026    , 0.0026    ,
       0.0019    , 0.03490403, 0.03365004, 0.0018    , 0.05861739,
       0.0022    , 0.0023    , 0.002     , 0.0023    , 0.00683235,
       0.0021    , 0.01258901, 0.0019    , 0.07840631])

In [68]:
emi_rate_new[i,:,:].shape

(86, 34)

In [67]:
full_death_table.shape

(86, 34)

In [66]:
full_death_table[0,:]

array([7.1, 5.8, 5.2, 5. , 4.3, 4.3, 3.5, 4. , 4.1, 3.2, 2.8, 2.4, 3.4,
       2.8, 2.2, 2.4, 2.8, 2.6, 2.6, 2.6, 1.9, 2.3, 2. , 1.8, 1.9, 2.2,
       2.3, 2. , 2.3, 1.8, 2.1, 1.6, 1.9, 1.9])

In [62]:
emi_rate_new[0,0,:]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.05706107,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.03260403, -0.03165004,  0.        , -0.05671739,
        0.        ,  0.        ,  0.        ,  0.        , -0.00503235,
        0.        , -0.01098901,  0.        , -0.07650631])

In [63]:
death_mig_cohort[0,0,:]

array([0.        , 0.0058    , 0.0003    , 0.0003    , 0.0004    ,
       0.0004    , 0.0002    , 0.0002    , 0.0001    , 0.0001    ,
       0.0001    , 0.0001    , 0.0001    , 0.00835426, 0.0001    ,
       0.0001    , 0.0002    , 0.00215937, 0.0003    , 0.0003    ,
       0.0002    , 0.0005    , 0.0005    , 0.0004    , 0.0004    ,
       0.0003    , 0.0004    , 0.0003    , 0.0003    , 0.0003    ,
       0.0003    , 0.0004    , 0.0005    , 0.0005    ])

In [20]:
full_death_table

array([[6.200e+00, 4.800e+00, 4.400e+00, ..., 1.900e+00, 1.600e+00,
        2.600e+00],
       [2.000e-01, 3.000e-01, 3.000e-01, ..., 1.000e-01, 1.000e-01,
        1.000e-01],
       [2.000e-01, 3.000e-01, 3.000e-01, ..., 1.000e-01, 1.000e-01,
        1.000e-01],
       ...,
       [7.860e+01, 7.100e+01, 7.290e+01, ..., 3.970e+01, 4.360e+01,
        4.100e+01],
       [7.860e+01, 7.100e+01, 7.290e+01, ..., 3.970e+01, 4.360e+01,
        4.100e+01],
       [1.294e+02, 1.252e+02, 1.270e+02, ..., 1.091e+02, 1.220e+02,
        1.206e+02]])

In [19]:
death_mig_cohort[1,:,:]

array([[0. , 4.8, 0.3, ..., 0.2, 0.3, 0.2],
       [0. , 0. , 4.4, ..., 0.2, 0.3, 0.2],
       [0. , 0. , 0. , ..., 0.2, 0.1, 0.2],
       ...,
       [0. , 0. , 0. , ..., 1.9, 0.1, 0.1],
       [0. , 0. , 0. , ..., 0. , 1.6, 0.1],
       [0. , 0. , 0. , ..., 0. , 0. , 2.6]])

In [ ]:
full_death_table is a 5 * 4 matrix 
nrows = 3
ncols = 4
for i in range(nrows):
         
        vec = np.zeros(ncols)
        for j in range(ncols):
            if j <= i:
                vec[j] = 1 # death is for sure 
            else:
                vec[j] = full_death_table[i+1+j,j]
        death_mig_cohort[i,:] = vec

In [11]:
# Assuming full_death_table is a 5x4 matrix initialized with some values
# full_death_table = np.array([
#     [0.1, 0.2, 0.3, 0.4],
#     [0.5, 0.6, 0.7, 0.8],
#     [0.9, 1.0, 1.1, 1.2],
#     [1.3, 1.4, 1.5, 1.6],
#     [1.7, 1.8, 1.9, 2.0]
# ])

# nrows = 3
# ncols = 4
# death_mig_cohort = np.zeros((nrows, ncols))

# for i in range(nrows):
#     vec = np.zeros(ncols)
#     for j in range(ncols):
#         if j <= i:
#             vec[j] = 1  # death is for sure
#         else:
#             idx = min(4,j+i+1)
#             vec[j] = full_death_table[idx, j]
#     death_mig_cohort[i, :] = vec

# print(death_mig_cohort)


[[1.  1.  1.5 2. ]
 [1.  1.  1.9 2. ]
 [1.  1.  1.  2. ]]


In [15]:
import numpy as np

def extract_padded_diagonals(full_death_table):
    nrows, ncols = full_death_table.shape
    max_len = ncols

    # To store diagonals, padded to length 4
    diagonals = []

    # Extract the diagonals and pad them with zeros
    for start_col in range(ncols):
        diag = []
        row, col = 0, start_col

        # Collect the diagonal elements starting from (0, start_col)
        while row < nrows and col < ncols:
            diag.append(full_death_table[row, col])
            row += 1
            col += 1

        # Pad with zeros if the length is less than 4
        while len(diag) < max_len:
            diag.insert(0, 0)

        diagonals.append(diag)

    # Skip the first diagonal and convert the rest to a matrix
    matrix_rows = []
    for diag in diagonals[1:]:  # Start from the second diagonal
        # Exclude the first value (which is padding, i.e., 0)
        matrix_rows.append(diag)

    # Create a NumPy matrix from the rows
    result_matrix = np.array(matrix_rows)

    return result_matrix

# Example usage
full_death_table = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5, 1.6],
    [1.7, 1.8, 1.9, 2.0]
])

result = extract_padded_diagonals(full_death_table)
print(result)


[[0.  0.2 0.7 1.2]
 [0.  0.  0.3 0.8]
 [0.  0.  0.  0.4]]


In [ ]:
nrows, ncols = full_death_table.shape
max_len = ncols

# To store diagonals, padded to length 4
diagonals = []

# Extract the diagonals and pad them with zeros
for start_col in range(ncols):
    diag = []
    row, col = 0, start_col
    
    # Collect the diagonal elements starting from (0, start_col)
    while row < nrows and col < ncols:
        diag.append(full_death_table[row, col])
        row += 1
        col += 1
    
    # Pad with zeros if the length is less than 4
    while len(diag) < max_len:
        diag.insert(0, 0)

    diagonals.append(diag)
    matrix_rows = []
    for diag in diagonals[1:]:  # Start from the second diagonal
    # Exclude the first value (which is padding, i.e., 0)
        matrix_rows.append(diag[1:])

# Create a NumPy matrix from the rows
result_matrix = np.array(matrix_rows)

In [13]:
matrix_rows = []
for diag in diagonals[1:]:  # Start from the second diagonal
    # Exclude the first value (which is padding, i.e., 0)
    matrix_rows.append(diag[1:])

# Create a NumPy matrix from the rows
result_matrix = np.array(matrix_rows)

## check fertility by ethnicity

In [148]:
import numpy as np

# Read the binary file
result_matrix = np.fromfile('result_matrix_data.bin')

# If you know the shape of the original matrix, you can reshape it
# Example, if your original matrix was 3x4:
result_matrix = result_matrix.reshape((8,86,35))

print(result_matrix)

result_matrix[0,:,:]

[[[1.6814e+04 1.8396e+04 1.7102e+04 ... 1.0472e+04 9.8860e+03 9.6520e+03]
  [1.9236e+04 1.7002e+04 1.8539e+04 ... 1.1289e+04 1.1210e+04 1.0620e+04]
  [1.7155e+04 1.9429e+04 1.7176e+04 ... 1.2529e+04 1.1616e+04 1.1460e+04]
  ...
  [9.8800e+02 1.0820e+03 1.0780e+03 ... 5.1730e+03 5.4010e+03 5.6550e+03]
  [7.4600e+02 8.7500e+02 9.6700e+02 ... 4.0250e+03 4.8150e+03 5.0550e+03]
  [2.7360e+03 2.9930e+03 3.3060e+03 ... 1.7685e+04 1.8905e+04 2.0867e+04]]

 [[1.5339e+04 1.7017e+04 1.6210e+04 ... 9.8980e+03 9.1860e+03 9.2040e+03]
  [1.8065e+04 1.5535e+04 1.7232e+04 ... 1.0714e+04 1.0724e+04 9.9170e+03]
  [1.5941e+04 1.8236e+04 1.5688e+04 ... 1.2118e+04 1.1031e+04 1.0975e+04]
  ...
  [1.6670e+03 1.7720e+03 1.8150e+03 ... 7.6120e+03 7.8620e+03 8.1160e+03]
  [1.3330e+03 1.4990e+03 1.6010e+03 ... 5.7050e+03 7.2850e+03 7.5310e+03]
  [6.0390e+03 6.4450e+03 6.8720e+03 ... 3.4690e+04 3.6154e+04 3.9118e+04]]

 [[5.0560e+03 5.1940e+03 4.9470e+03 ... 4.2460e+03 3.9960e+03 3.7050e+03]
  [4.9210e+03 5.0560e+

array([[16814., 18396., 17102., ..., 10472.,  9886.,  9652.],
       [19236., 17002., 18539., ..., 11289., 11210., 10620.],
       [17155., 19429., 17176., ..., 12529., 11616., 11460.],
       ...,
       [  988.,  1082.,  1078., ...,  5173.,  5401.,  5655.],
       [  746.,   875.,   967., ...,  4025.,  4815.,  5055.],
       [ 2736.,  2993.,  3306., ..., 17685., 18905., 20867.]])

In [153]:
death_by_cohort = np.fromfile('data/bin/death_by_cohort.bin')

death_by_cohort = death_by_cohort.reshape((2,86,34))
# death_by_cohort = death_by_cohort/ 1000
# death_by_cohort.tofile('data/bin/death_by_cohort.bin')
print(death_by_cohort[0,:,:])

[[0.0071 0.0003 0.0003 ... 0.0004 0.0005 0.0005]
 [0.0004 0.0003 0.0003 ... 0.0004 0.0005 0.0005]
 [0.0004 0.0003 0.0003 ... 0.0004 0.0005 0.0006]
 ...
 [0.0972 0.1031 0.1471 ... 0.1405 0.1528 0.1371]
 [0.0972 0.1351 0.1471 ... 0.1405 0.1528 0.1371]
 [0.1423 0.1351 0.1471 ... 0.1405 0.1528 0.1371]]


In [152]:
death_by_cohort

In [207]:
import numpy as np

# Open the binary file for reading
with open('data/bin/AESFR_matrix_combine_R.bin', 'rb') as file:
    # Read the binary data as float64 (which corresponds to R's 'numeric' type)
    my_matrix = np.fromfile(file, dtype=np.float64)

# Reshape the flat array back to its original matrix dimensions (if known)
my_matrix = my_matrix.reshape((12,71,35), order='f')  # Example reshape based on dimensions in R

print(my_matrix)



[[[0.00000000e+00 0.00000000e+00 1.02301934e-02 ... 1.78323077e-04
   3.45904945e-04 6.61202198e-04]
  [0.00000000e+00 0.00000000e+00 9.09343146e-03 ... 2.19914607e-04
   2.86714607e-04 4.14310112e-04]
  [0.00000000e+00 0.00000000e+00 8.80851724e-03 ... 2.66462069e-04
   3.15201724e-04 3.22324138e-04]
  ...
  [2.24187342e-05 4.83988152e-05 1.00402107e-04 ... 2.86912159e-03
   1.72946640e-03 1.00175278e-03]
  [1.76237662e-05 3.82139094e-05 7.96211873e-05 ... 2.59420051e-03
   1.57060043e-03 9.13720045e-04]
  [1.64932440e-05 3.59201435e-05 7.51717149e-05 ... 2.79448610e-03
   1.69931249e-03 9.92955594e-04]]

 [[0.00000000e+00 0.00000000e+00 1.02301934e-02 ... 1.78323077e-04
   3.45904945e-04 6.61202198e-04]
  [0.00000000e+00 0.00000000e+00 9.09343146e-03 ... 2.19914607e-04
   2.86714607e-04 4.14310112e-04]
  [0.00000000e+00 0.00000000e+00 8.80851724e-03 ... 2.66462069e-04
   3.15201724e-04 3.22324138e-04]
  ...
  [4.72977782e-05 1.02109085e-04 2.11822690e-04 ... 6.05311056e-03
   3.64873

In [216]:
my_matrix[0,0,:]

array([0.        , 0.        , 0.01023019, 0.02232308, 0.03563439,
       0.04982609, 0.06477044, 0.08042979, 0.09651119, 0.11197073,
       0.12806729, 0.14153206, 0.14693071, 0.14172217, 0.12851975,
       0.11230518, 0.09682772, 0.08185324, 0.06882834, 0.05747673,
       0.0456316 , 0.03349166, 0.02372666, 0.01714221, 0.01308479,
       0.01007744, 0.0072641 , 0.00507498, 0.0032832 , 0.00186621,
       0.00087099, 0.00031995, 0.00017832, 0.0003459 , 0.0006612 ])

In [209]:
my_matrix.tofile("data/bin/AESFR_matrix_combine.bin")

In [210]:
py_mat = np.fromfile("data/bin/AESFR_matrix_combine.bin")

In [211]:
py_mat

array([0.        , 0.        , 0.01023019, ..., 0.        , 0.        ,
       0.        ])

In [212]:
py_mat = py_mat.reshape((12,71,35))

In [215]:
py_mat[0,0,:]

array([0.        , 0.        , 0.01023019, 0.02232308, 0.03563439,
       0.04982609, 0.06477044, 0.08042979, 0.09651119, 0.11197073,
       0.12806729, 0.14153206, 0.14693071, 0.14172217, 0.12851975,
       0.11230518, 0.09682772, 0.08185324, 0.06882834, 0.05747673,
       0.0456316 , 0.03349166, 0.02372666, 0.01714221, 0.01308479,
       0.01007744, 0.0072641 , 0.00507498, 0.0032832 , 0.00186621,
       0.00087099, 0.00031995, 0.00017832, 0.0003459 , 0.0006612 ])

In [ ]:
y_idx = 1990 - 1980 + 1


In [192]:
import numpy as np

# Open the binary file for reading
with open('matrix.bin', 'rb') as file:
    # Read the binary data as float64 (to match R's numeric type)
    my_3d_array = np.fromfile(file, dtype=np.float64)

# Reshape the array back to its original dimensions (e.g., 2x3x4), using 'F' for column-major order
my_3d_array = my_3d_array.reshape((3, 3, 3))

print(my_3d_array)

[[[0.00e+000 4.94e-324 9.88e-324]
  [1.48e-323 1.98e-323 2.47e-323]
  [2.96e-323 3.46e-323 3.95e-323]]

 [[4.45e-323 4.94e-323 5.43e-323]
  [5.93e-323 6.42e-323 6.92e-323]
  [7.41e-323 7.91e-323 8.40e-323]]

 [[8.89e-323 9.39e-323 9.88e-323]
  [1.04e-322 1.09e-322 1.14e-322]
  [1.19e-322 1.24e-322 1.28e-322]]]


In [201]:
# check how numpy read 3 d matrix 
my_matrix = np.random.rand(2, 3, 4)  # Generate random double values
print(my_matrix)
# Save the matrix in binary format
my_matrix.tofile('matrix_double.bin')  # This saves in row-major order


[[[0.13771182 0.96331936 0.78856916 0.72585672]
  [0.2508122  0.20650654 0.61734712 0.26016259]
  [0.40417671 0.49459359 0.1268885  0.47895454]]

 [[0.25455488 0.17000219 0.98256908 0.67043197]
  [0.75892632 0.18376291 0.02878492 0.06936708]
  [0.7725191  0.62083898 0.26561578 0.82341443]]]


In [202]:
with open('matrix_double.bin', 'rb') as file:
    # Read the binary data as float64 (to match R's numeric type)
    my_2d_array = np.fromfile(file, dtype=np.float64)


In [203]:
my_2d_array

array([0.13771182, 0.96331936, 0.78856916, 0.72585672, 0.2508122 ,
       0.20650654, 0.61734712, 0.26016259, 0.40417671, 0.49459359,
       0.1268885 , 0.47895454, 0.25455488, 0.17000219, 0.98256908,
       0.67043197, 0.75892632, 0.18376291, 0.02878492, 0.06936708,
       0.7725191 , 0.62083898, 0.26561578, 0.82341443])