In [5]:
import numpy as np
import os

# Directory containing the binary files
data_dir = "../output/20250525_223427"

# List to store the 8 matrices
matrices = []

# Read each binary file
for i in range(8):
    filename = os.path.join(data_dir, f"forecast_matrix_{i}.bin")
    
    # Get file size to determine number of rows
    file_size = os.path.getsize(filename)
    num_rows = file_size // (27 * 4)  # 27 columns, 4 bytes per int32
    
    # Create numpy matrix of appropriate size
    matrix = np.zeros((num_rows, 27), dtype=np.int32)
    
    # Read binary data into matrix
    with open(filename, 'rb') as f:
        # Read all values at once into flattened array
        data = np.fromfile(f, dtype=np.int32)
        # Reshape into matrix
        matrix = data.reshape((num_rows, 27))
    
    matrices.append(matrix)
    print(f"Matrix {i} shape: {matrix.shape}")

Matrix 0 shape: (0, 27)
Matrix 1 shape: (0, 27)
Matrix 2 shape: (20316, 27)
Matrix 3 shape: (20492, 27)
Matrix 4 shape: (0, 27)
Matrix 5 shape: (0, 27)
Matrix 6 shape: (0, 27)
Matrix 7 shape: (0, 27)


In [6]:
# Print matrix 3 (index 2 since 0-based)
print("\nMatrix 3 contents:")
print(matrices[2])



Matrix 3 contents:
[[-1 -1 -1 ... -1 -1 -1]
 [34 35 36 ... 58 59 60]
 [34 35 36 ... 58 59 60]
 ...
 [-1 -1 -1 ... -1 -1  0]
 [-1 -1 -1 ... -1 -1  0]
 [-1 -1 -1 ... -1 -1  0]]


In [7]:
# Export matrix 2 to CSV
np.savetxt('matrix_2.csv', matrices[2], delimiter=',', fmt='%d')
print("Matrix 2 exported to matrix_2.csv")

Matrix 2 exported to matrix_2.csv


## to do:

In [10]:
# Define shape of immigration data (8 matrices, 50 age groups, 27 years)
immigration_shape = (8, 50, 27)

# Read immigration data from binary file
with open('../data/migration/future_immigration.bin', 'rb') as f:
    immigration_data = np.fromfile(f, dtype=np.int32).reshape(immigration_shape)

# Display the immigration data
print(f"Immigration data shape: {immigration_data.shape}")
print("\nFirst few values:")
print(immigration_data[0, :3, :3])  # Show first 3 age groups x 3 years for first matrix

Immigration data shape: (8, 50, 27)

First few values:
[[36 41 34]
 [17  6  9]
 [ 4  8  5]]


In [11]:
immigration_data[2]

array([[3, 4, 4, ..., 3, 4, 4],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [12]:
14654 + 1399 

16053

In [ ]:
1200 * 20 = 24000, compared with 30,808 births in 2024