## load immigration information

In [1]:
import pandas as pd
import numpy as np

# Create a list to store gration matrices
migration_matrices = []

# Read each migration CSV file
for i in range(8):
    filename = f"../data/migration/migration_{i}.csv"
    migration_matrix = pd.read_csv(filename, header=None)
    migration_matrices.append(migration_matrix)


ModuleNotFoundError: No module named 'pandas'

In [2]:
migration_matrices[0]

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,11,7,13,12,15,14,13,15,17,...,57,53,52,54,51,49,46,47,39,37
2,0,10,8,9,7,8,9,8,10,10,...,13,15,15,24,19,19,14,7,22,16
3,0,9,9,9,5,7,9,7,7,8,...,8,14,14,13,13,12,8,2,21,15
4,0,6,5,7,7,6,5,8,10,7,...,6,9,11,12,7,9,7,1,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
83,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
84,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


# load population information

In [3]:
# Load and reshape result_matrix
# this is for 1990 - 2024; 
result_matrix = np.fromfile("../data/bin/result_matrix_data.bin", dtype=np.float64)  # Specify data type if needed
result_matrix = result_matrix.reshape(8, 86, 35)  # Reshape to correct dimensions (8 cohorts, 86 ages, 35 years)

In [4]:
scaled_popu = result_matrix / 20 

In [5]:
scaled_popu[6,:,:]

array([[22.45, 29.  , 26.65, ..., 24.2 , 22.65, 21.1 ],
       [22.15, 22.2 , 28.2 , ..., 30.  , 27.45, 26.1 ],
       [19.8 , 21.95, 21.9 , ..., 33.3 , 32.85, 29.15],
       ...,
       [ 0.95,  0.9 ,  0.7 , ...,  3.1 ,  4.  ,  3.65],
       [ 0.6 ,  0.9 ,  0.85, ...,  2.3 ,  2.8 ,  3.75],
       [ 1.9 ,  2.15,  2.5 , ..., 17.65, 18.1 , 18.25]])

In [6]:
# Get column sums for scaled_popu[6,:,:] and scaled_popu[0,:,:]
col_sum_6 = np.sum(scaled_popu[6,:,:], axis=0)
col_sum_0 = np.sum(scaled_popu[0,:,:], axis=0)
col_sum_2 = np.sum(scaled_popu[2,:,:], axis=0)
col_sum_4 = np.sum(scaled_popu[4,:,:], axis=0)

print("Column sums for scaled_popu[6,:,:]:")
print(col_sum_6)
print("\nColumn sums for scaled_popu[0,:,:]:")
print(col_sum_0)
print("\nColumn sums for scaled_popu[2,:,:]:")
print(col_sum_2)
print("\nColumn sums for scaled_popu[4,:,:]:")
print(col_sum_4)


Column sums for scaled_popu[6,:,:]:
[ 714.5   749.8   779.7   807.    837.1   863.2   894.9   938.85  984.65
 1038.45 1090.9  1154.2  1254.45 1295.3  1424.2  1663.15 1933.6  2215.45
 2461.5  2863.2  2991.9  2986.5  2995.7  3012.8  3004.4  2995.65 2989.15
 2976.55 2974.05 2969.9  2965.75 2896.15 3022.75 3147.05 3201.05]

Column sums for scaled_popu[0,:,:]:
[53552.75 54627.65 55557.6  56500.45 57403.4  58317.1  59243.25 60117.6
 60994.3  61766.45 62483.1  63350.95 64168.1  63662.8  64277.85 64892.45
 65543.65 66235.75 66979.8  68011.2  68504.15 68783.25 69280.3  69759.15
 70196.35 70765.15 71262.2  71814.2  72268.75 72785.4  73067.2  72042.7
 73318.3  74451.4  74882.75]

Column sums for scaled_popu[2,:,:]:
[ 9797.5   9992.1  10172.75 10357.05 10543.   10708.5  10868.2  11021.2
 11170.25 11315.55 11442.5  11598.5  11753.8  11779.85 11911.8  12020.3
 12137.95 12248.45 12350.85 12455.75 12544.25 12611.35 12678.9  12758.8
 12851.8  12955.4  13078.2  13195.6  13324.3  13446.65 13566.6  13587.

In [7]:
74882.75 / 3201


23.393548890971573

In [8]:
74/ 13

5.6923076923076925

In [9]:
scaled_popu[0,:,:]

array([[ 840.7 ,  919.8 ,  855.1 , ...,  523.6 ,  494.3 ,  482.6 ],
       [ 961.8 ,  850.1 ,  926.95, ...,  564.45,  560.5 ,  531.  ],
       [ 857.75,  971.45,  858.8 , ...,  626.45,  580.8 ,  573.  ],
       ...,
       [  49.4 ,   54.1 ,   53.9 , ...,  258.65,  270.05,  282.75],
       [  37.3 ,   43.75,   48.35, ...,  201.25,  240.75,  252.75],
       [ 136.8 ,  149.65,  165.3 , ...,  884.25,  945.25, 1043.35]])

In [10]:
result_matrix[0]

array([[16814., 18396., 17102., ..., 10472.,  9886.,  9652.],
       [19236., 17002., 18539., ..., 11289., 11210., 10620.],
       [17155., 19429., 17176., ..., 12529., 11616., 11460.],
       ...,
       [  988.,  1082.,  1078., ...,  5173.,  5401.,  5655.],
       [  746.,   875.,   967., ...,  4025.,  4815.,  5055.],
       [ 2736.,  2993.,  3306., ..., 17685., 18905., 20867.]])

In [11]:
result_matrix[0] * 20

array([[336280., 367920., 342040., ..., 209440., 197720., 193040.],
       [384720., 340040., 370780., ..., 225780., 224200., 212400.],
       [343100., 388580., 343520., ..., 250580., 232320., 229200.],
       ...,
       [ 19760.,  21640.,  21560., ..., 103460., 108020., 113100.],
       [ 14920.,  17500.,  19340., ...,  80500.,  96300., 101100.],
       [ 54720.,  59860.,  66120., ..., 353700., 378100., 417340.]])

In [12]:
scaled_popu[0].shape

(86, 35)

In [13]:
scaled_popu[0][:,-3] # 年份对错了

array([ 523.6 ,  564.45,  626.45,  625.3 ,  631.95,  668.9 ,  709.4 ,
        725.1 ,  683.6 ,  750.15,  725.35,  665.65,  696.3 ,  709.85,
        735.9 ,  706.85,  702.55,  699.8 ,  691.75,  742.2 ,  748.25,
        867.  ,  842.75,  795.2 ,  875.7 ,  921.85,  980.15, 1022.5 ,
       1063.9 , 1082.45, 1074.6 , 1159.9 , 1109.95, 1240.5 , 1123.95,
        950.15,  997.45, 1041.65,  992.95, 1065.3 , 1073.1 , 1043.9 ,
       1036.5 , 1042.4 ,  994.3 , 1075.4 , 1030.1 , 1024.85, 1089.3 ,
       1144.55, 1095.8 , 1071.75, 1006.7 ,  992.1 , 1042.35, 1037.6 ,
       1107.45, 1110.05, 1136.65, 1123.4 , 1101.95, 1117.9 , 1109.9 ,
       1107.35, 1073.2 , 1073.1 , 1019.8 ,  973.65,  965.4 ,  888.45,
        830.3 ,  780.4 ,  764.35,  733.45,  659.7 ,  629.5 ,  424.5 ,
        314.65,  376.3 ,  316.1 ,  286.5 ,  319.75,  288.45,  258.65,
        201.25,  884.25])

In [14]:
scaled_popu[0][18:76,-1] # 年份对错了

array([ 716.5 ,  712.6 ,  697.5 ,  741.5 ,  745.45,  868.75,  856.75,
        825.75,  924.55,  981.1 , 1040.  , 1083.6 , 1119.1 , 1134.2 ,
       1122.55, 1203.8 , 1151.75, 1278.7 , 1156.9 ,  986.65, 1027.95,
       1073.05, 1022.4 , 1092.1 , 1098.2 , 1063.1 , 1054.95, 1060.7 ,
       1012.35, 1091.75, 1043.15, 1037.35, 1102.4 , 1157.45, 1107.15,
       1081.5 , 1014.75, 1000.4 , 1049.7 , 1041.4 , 1113.3 , 1112.8 ,
       1140.75, 1127.45, 1100.15, 1116.2 , 1103.1 , 1100.1 , 1061.9 ,
       1059.75, 1005.7 ,  957.85,  941.85,  866.6 ,  807.5 ,  754.7 ,
        739.55,  706.25])

In [15]:
np.sum(scaled_popu[2])

424030.35000000003

In [16]:
np.sum(scaled_popu[4])

271712.30000000005

In [17]:
scaled_popu.shape

(8, 86, 35)

## calculate immigration rates

### age-specific

In [18]:
immigration_rates = []
for i in range(8):
    # Get dimensions
    rows, cols = migration_matrices[i].shape
    immigration_rate = np.zeros((rows, cols))
    
    # Convert migration matrix to numpy array for faster operations
    migration_array = migration_matrices[i].to_numpy()
    # Use numpy where to handle division by zero
    immigration_rate = np.where(scaled_popu[i][:,1:] != 0, 
                              migration_array / scaled_popu[i][:,1:],
                              0)
                
    immigration_rates.append(immigration_rate)

# Print first immigration rate matrix
print("Immigration rate matrix for first ethnic group:")
print(immigration_rates[0])

Immigration rate matrix for first ethnic group:
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.01186688 0.00806452 ... 0.0832669  0.06958073 0.06967985]
 [0.         0.01164415 0.00855615 ... 0.01117408 0.03787879 0.02792321]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


### across all the ages

In [19]:
total_immigration_rates = []
for i in range(8):
    # Get dimensions
    rows, cols = migration_matrices[i].shape
    
    # Calculate column sums
    migration_colsum = np.sum(migration_matrices[i].to_numpy(), axis=0)
    population_colsum = np.sum(scaled_popu[i][:,1:], axis=0)
    
    # Calculate total immigration rate using numpy where to handle division by zero
    total_immigration_rate = np.where(population_colsum != 0,
                                    migration_colsum / population_colsum,
                                    0)
    
    total_immigration_rates.append(total_immigration_rate)

# Print total immigration rates for all ethnic groups
for i in range(8):
    print(f"Total immigration rate for ethnic group {i}:")
    print(total_immigration_rates[i])

Total immigration rate for ethnic group 0:
[0.         0.00786571 0.00676101 0.0060972  0.00536721 0.00578969
 0.00647065 0.00593498 0.00636268 0.00622568 0.00494073 0.00659206
 0.00772822 0.00088678 0.00491583 0.00535521 0.00543513 0.00641985
 0.00661656 0.01080227 0.0040853  0.00230946 0.00484524 0.00410278
 0.00486115 0.00533242 0.00448379 0.00596385 0.00491857 0.00587131
 0.00426136 0.00290514 0.01368678 0.01187189]
Total immigration rate for ethnic group 1:
[0.         0.00976535 0.00962988 0.0092042  0.00855495 0.00879569
 0.0079817  0.00891929 0.00918771 0.00817918 0.00695688 0.00880441
 0.01075922 0.00275441 0.00600508 0.00615391 0.00764893 0.00784267
 0.0098576  0.01491681 0.00614272 0.0032495  0.00686975 0.00559011
 0.00604834 0.00674265 0.00572763 0.0070608  0.00594278 0.00744132
 0.00488389 0.00224142 0.01685106 0.01516522]
Total immigration rate for ethnic group 2:
[0.         0.00049151 0.00096553 0.00047425 0.00037354 0.00064408
 0.00081661 0.00044762 0.00053024 0.000349

In [20]:
print(immigration_rates[0][1:51,-14:-4])

[[0.06623561 0.08114249 0.07938291 0.07399347 0.09011858 0.07913401
  0.07856172 0.08635855 0.08519168 0.08200837]
 [0.00906481 0.00918555 0.03025478 0.01911484 0.01844102 0.02316423
  0.02164502 0.03527078 0.02949395 0.03101028]
 [0.00712099 0.00738389 0.0240692  0.0172793  0.01151742 0.01952172
  0.02119767 0.01842404 0.01877392 0.01838376]
 [0.00738716 0.00561443 0.01459534 0.01193228 0.00929368 0.01276415
  0.01507985 0.01797887 0.00980118 0.01287001]
 [0.00589362 0.00583218 0.01259798 0.00434436 0.00738498 0.01071729
  0.01122098 0.00947803 0.01333037 0.01113741]
 [0.00733192 0.00438308 0.008726   0.00277643 0.00860277 0.0102242
  0.01056524 0.01250695 0.00936705 0.01324503]
 [0.0059831  0.00145953 0.00582623 0.00289855 0.0041405  0.00569679
  0.00723589 0.01050578 0.00552906 0.00534509]
 [0.00139189 0.00297974 0.0043735  0.         0.00288164 0.00549828
  0.00424268 0.00720409 0.00449674 0.00137751]
 [0.00137779 0.0458397  0.00148787 0.00145296 0.00433088 0.00575126
  0.00136584 

In [21]:
# Get non-zero values and calculate mean for each row
non_zero_means = np.array([row[row != 0].mean() if np.any(row != 0) else 0 
                          for row in immigration_rates[0][1:51,-14:-4]])
non_zero_means

array([0.08021274, 0.02266453, 0.01636719, 0.0117317 , 0.00919372,
       0.00877287, 0.00546205, 0.00382734, 0.00745925, 0.00226592,
       0.00932679, 0.00327513, 0.00273663, 0.00195507, 0.01072399,
       0.00275912, 0.00333486, 0.0040098 , 0.00299223, 0.00161703,
       0.00109308, 0.00688299, 0.00556728, 0.01386195, 0.02338814,
       0.02435423, 0.02439909, 0.02251391, 0.01894305, 0.01551378,
       0.01271834, 0.00944751, 0.0077973 , 0.00738784, 0.00456161,
       0.00418209, 0.00237665, 0.00323294, 0.00224577, 0.00185357,
       0.00224798, 0.00193412, 0.00271592, 0.00181522, 0.00263812,
       0.00150578, 0.00156219, 0.        , 0.        , 0.        ])

# fit a uniform distribution to immigration rates

### we used rates from 2010 - 2019 (-14 to -4)

In [22]:
immigration_rates[0][1,:]

array([0.        , 0.01186688, 0.00806452, 0.01447903, 0.01336824,
       0.01686056, 0.01613926, 0.01531664, 0.01812032, 0.02265609,
       0.02023907, 0.06056486, 0.06637328, 0.05278592, 0.05373795,
       0.05092593, 0.05845704, 0.05819741, 0.0462963 , 0.05951019,
       0.06623561, 0.08114249, 0.07938291, 0.07399347, 0.09011858,
       0.07913401, 0.07856172, 0.08635855, 0.08519168, 0.08200837,
       0.07593265, 0.0832669 , 0.06958073, 0.06967985])

In [23]:
immigration_rates[0][1,-14:-4]

array([0.06623561, 0.08114249, 0.07938291, 0.07399347, 0.09011858,
       0.07913401, 0.07856172, 0.08635855, 0.08519168, 0.08200837])

In [24]:
# Initialize arrays to store uniform distribution parameters for all ethnic groups
uniform_params = np.zeros((8, 50, 2))  # Shape: (8 ethnic groups, 50 ages, 2 params)

# For each ethnic group
for i in range(8):
    # Get the immigration rates data for this ethnic group
    # -4 is the year 2019, pre-covid 
    imm_rates = immigration_rates[i][1:51,-14:-4]
    
    # For each row (age), fit uniform distribution to non-zero values
    for j, row in enumerate(imm_rates):
        non_zero_vals = row[row != 0]
        if len(non_zero_vals) > 0:
            # Get min and max for uniform distribution
            min_val = np.min(non_zero_vals)
            max_val = np.max(non_zero_vals)
            uniform_params[i,j] = [min_val, max_val]

print("Uniform distribution parameters shape:", uniform_params.shape)
print("Parameters for first ethnic group:")
print(uniform_params[i])

# Example of generating samples using the parameters
def generate_samples(params, n_samples=20):
    samples = np.zeros((8, 50, n_samples))
    for i in range(8):
        for j in range(50):
            min_val, max_val = params[i,j]
            if min_val != 0 or max_val != 0:
                samples[i,j] = np.random.uniform(min_val, max_val, n_samples)
    return samples

# Generate some sample data
sample_data = generate_samples(uniform_params)
print("\nGenerated samples shape:", sample_data.shape)

Uniform distribution parameters shape: (8, 50, 2)
Parameters for first ethnic group:
[[0.1610306  0.43956044]
 [0.02985075 0.14025245]
 [0.02631579 0.0862069 ]
 [0.01826484 0.05494505]
 [0.01780944 0.10217114]
 [0.02475248 0.05565863]
 [0.04592423 0.21032505]
 [0.01956947 0.02512563]
 [0.01956947 0.13685239]
 [0.         0.        ]
 [0.02103049 0.22869023]
 [0.02012072 0.02012072]
 [0.01956947 0.21956088]
 [0.04581901 0.04581901]
 [0.02150538 0.17877095]
 [0.02684564 0.02684564]
 [0.03039514 0.19911504]
 [0.02971768 0.02971768]
 [0.1242236  0.1242236 ]
 [0.03355705 0.03355705]
 [0.07246377 0.15915119]
 [0.1        0.1       ]
 [0.03039514 0.38123167]
 [0.02915452 0.06779661]
 [0.02805049 0.41800643]
 [0.03039514 0.11299435]
 [0.0538358  0.1314554 ]
 [0.02152853 0.13114754]
 [0.04012036 0.13143483]
 [0.01574803 0.11022658]
 [0.01501502 0.09596929]
 [0.02728513 0.08880995]
 [0.02677376 0.06779661]
 [0.02743484 0.03929273]
 [0.01256281 0.04459309]
 [0.01183432 0.05440696]
 [0.01135074 0.

In [27]:
np.save('uniform_immigration_params.npy', uniform_params)
# or
uniform_params.tofile('uniform_immigration_params.bin')

In [26]:
import pandas as pd

# Create a comprehensive dataframe with uniform distribution parameters
# for all ethnic groups and ages

# Create lists to store data for DataFrame
data = []

# Iterate through all ethnic groups and ages
for ethnic_group in range(8):
    for age in range(50):
        data.append({
            'ethnic_group': ethnic_group,
            'age': age + 1,  # Ages 1-50
            'min_param': uniform_params[ethnic_group, age, 0],
            'max_param': uniform_params[ethnic_group, age, 1],
           
        })

# Create DataFrame
immigration_params_df = pd.DataFrame(data)

# Display basic information about the dataframe
print("Immigration Parameters DataFrame:")
print(f"Shape: {immigration_params_df.shape}")
print("\nFirst 10 rows:")
print(immigration_params_df.head(10))

# print("\nSample statistics:")
# print(immigration_params_df.describe())

# # Show parameters for a specific ethnic group
# print(f"\nParameters for ethnic group 0:")
# ethnic_0_df = immigration_params_df[immigration_params_df['ethnic_group'] == 0]
# print(ethnic_0_df.head(10))


Immigration Parameters DataFrame:
Shape: (400, 4)

First 10 rows:
   ethnic_group  age  min_param  max_param
0             0    1   0.066236   0.090119
1             0    2   0.009065   0.035271
2             0    3   0.007121   0.024069
3             0    4   0.005614   0.017979
4             0    5   0.004344   0.013330
5             0    6   0.002776   0.013245
6             0    7   0.001460   0.010506
7             0    8   0.001378   0.007204
8             0    9   0.001366   0.045840
9             0   10   0.001176   0.004300


In [27]:
immigration_params_df[immigration_params_df["ethnic_group"] == 2]

,ethnic_group,age,min_param,max_param
100,2,1,0.019503,0.032310
101,2,2,0.004871,0.006483
102,2,3,0.005294,0.006427
103,2,4,0.006146,0.006479
104,2,5,0.000000,0.000000
105,2,6,0.006124,0.006384
106,2,7,0.006150,0.006464
107,2,8,0.006386,0.006386
108,2,9,0.006116,0.043034
109,2,10,0.005838,0.006347


In [25]:
# 8 ethnic groups, 50 ages, 2 params

uniform_params[2]

array([[0.01950268, 0.03231018],
       [0.00487092, 0.00648298],
       [0.00529381, 0.00642674],
       [0.00614628, 0.00647878],
       [0.        , 0.        ],
       [0.0061237 , 0.00638366],
       [0.00615006, 0.00646412],
       [0.0063857 , 0.0063857 ],
       [0.00611621, 0.04303389],
       [0.00583771, 0.00634719],
       [0.00583942, 0.02944785],
       [0.        , 0.        ],
       [0.00539665, 0.05105593],
       [0.00582242, 0.00582242],
       [0.00462856, 0.04712535],
       [0.00538068, 0.00538068],
       [0.0046307 , 0.05790646],
       [0.00435066, 0.00971581],
       [0.00418323, 0.01777383],
       [0.00443853, 0.00443853],
       [0.03040174, 0.03040174],
       [0.        , 0.        ],
       [0.00394089, 0.01276867],
       [0.00396983, 0.00418498],
       [0.00393856, 0.00393856],
       [0.00386324, 0.00386324],
       [0.00405927, 0.00405927],
       [0.        , 0.        ],
       [0.00402576, 0.0049456 ],
       [0.        , 0.        ],
       [0.

## example of generating migration people

In [20]:
import numpy as np

# Suppose popuvector is already defined, e.g.:
popuvector = scaled_popu[0][:, 30]  # for some year_index

# Generate a random immigration rate for each age 1-50 using uniform_params[0]
random_rates = np.array([
    np.random.uniform(low, high) 
    for low, high in uniform_params[0]
])

# Calculate the number of immigrants for each age (1-50)
# (popuvector[1:51] because age 0 is usually not used)
immigrants = (popuvector[1:51] * random_rates).astype(int)

print("Random immigration rates (ages 1-50):", random_rates)
print("Population vector (ages 1-50):", popuvector[1:51])
print("Immigrant counts (ages 1-50):", immigrants)

Random immigration rates (ages 1-50): [0.07741741 0.02615015 0.00894455 0.01354114 0.00440521 0.00416335
 0.00746187 0.00603389 0.0284461  0.00224245 0.00815029 0.00676097
 0.00516109 0.0023958  0.01636528 0.00420386 0.00244423 0.00875601
 0.00372911 0.00155353 0.00109308 0.00688299 0.01159633 0.0126206
 0.01283065 0.00762801 0.02213673 0.02389206 0.01399627 0.00804577
 0.00343935 0.00681239 0.01135766 0.0065075  0.00362048 0.00383592
 0.00221512 0.0050305  0.00279133 0.00263729 0.00226537 0.00222609
 0.00271592 0.0010335  0.00264513 0.00173411 0.0018537  0.
 0.         0.        ]
Population vector (ages 1-50): [ 597.5   612.7   652.75  699.3   718.3   679.5   748.35  725.95  667.45
  697.65  711.15  736.    700.4   701.2   698.95  683.65  732.4   742.3
  867.35  847.5   800.2   874.    904.9   938.85  973.2  1007.9  1032.3
 1032.5  1122.55 1082.45 1214.7  1105.7   935.35  986.05 1032.05  988.55
 1063.3  1074.1  1045.   1041.85 1047.45 1003.   1085.5  1040.3  1038.4
 1106.6  1159.6  1

In [21]:
# # Get the immigration rates data
# imm_rates = immigration_rates[0][1:51,-14:-4]

# # Calculate mean and standard deviation for each column
# means = np.mean(imm_rates, axis=0)
# stds = np.std(imm_rates, axis=0)

# # Calculate 95% confidence intervals
# z_score = 1.96  # For 95% CI
# ci_lower = means - z_score * stds / np.sqrt(len(imm_rates))
# ci_upper = means + z_score * stds / np.sqrt(len(imm_rates))

# # Ensure no negative values in confidence intervals
# ci_lower = np.maximum(ci_lower, 0)
# ci_upper = np.maximum(ci_upper, 0)

# # Store results
# confidence_intervals = np.vstack([ci_lower, ci_upper])



# load fertility rates

In [28]:
# Load and reshape fertility_matrix
fertility_matrix = np.fromfile("../data/bin/AESFR_matrix_combine.bin", dtype=np.float64)  # Specify data type if needed
fertility_matrix = fertility_matrix.reshape(12, 71, 35)  # Reshape to correct dimensions (12 groups, 71 years, 35 age)
1980 - 2050 

-70

In [ ]:
def map_fertility_rate(index, year, age, fertility_rates):
    if age < 15 or age >= 49:
        return 0.0
    return fertility_rates[index][year - 1980][age - 15]

# index = 1
#   # ages 15-49
# j = 2030
# rates = [map_fertility_rate(index // 2, j, age, fertility_matrix) for age in ages]

NameError: name 'ages' is not defined

In [30]:
fertility_matrix[0]

array([[0.00000000e+00, 0.00000000e+00, 1.02301934e-02, ...,
        1.78323077e-04, 3.45904945e-04, 6.61202198e-04],
       [0.00000000e+00, 0.00000000e+00, 9.09343146e-03, ...,
        2.19914607e-04, 2.86714607e-04, 4.14310112e-04],
       [0.00000000e+00, 0.00000000e+00, 8.80851724e-03, ...,
        2.66462069e-04, 3.15201724e-04, 3.22324138e-04],
       ...,
       [2.24187342e-05, 4.83988152e-05, 1.00402107e-04, ...,
        2.86912159e-03, 1.72946640e-03, 1.00175278e-03],
       [1.76237662e-05, 3.82139094e-05, 7.96211873e-05, ...,
        2.59420051e-03, 1.57060043e-03, 9.13720045e-04],
       [1.64932440e-05, 3.59201435e-05, 7.51717149e-05, ...,
        2.79448610e-03, 1.69931249e-03, 9.92955594e-04]])

In [31]:
# Read the saved data back 
with open('mortality_forecast_from_24.bin', 'rb') as f:
    mortality_forecast_from_24 = np.fromfile(f).reshape(2, 18, 27)

# 1-4, 5- 10, 11- 14, ...80- 84, 85+

In [32]:
is_female = 1  # 1 is female, 0 is male
year_index = 0 # index 0 is year 2024
mortaility_rate = mortality_forecast_from_24[is_female, np.arange(1, 85) // 5, year_index] / 1000.
mortality_forecast_from_24[0, 85 // 5, year_index] / 1000.

0.12143978091915869

In [33]:
mortality_forecast_from_24[0, 85 // 5, year_index] / 1000.

0.12143978091915869

warning:

mortality rates are from age 1;
while population is from age 0

In [ ]:
mortaility_rate

array([9.33458833e-05, 9.33458833e-05, 9.33458833e-05, 9.33458833e-05,
       9.53570783e-05, 9.53570783e-05, 9.53570783e-05, 9.53570783e-05,
       9.53570783e-05, 9.31014253e-05, 9.31014253e-05, 9.31014253e-05,
       9.31014253e-05, 9.31014253e-05, 1.21111713e-04, 1.21111713e-04,
       1.21111713e-04, 1.21111713e-04, 1.21111713e-04, 1.41786837e-04,
       1.41786837e-04, 1.41786837e-04, 1.41786837e-04, 1.41786837e-04,
       1.75179498e-04, 1.75179498e-04, 1.75179498e-04, 1.75179498e-04,
       1.75179498e-04, 2.51172413e-04, 2.51172413e-04, 2.51172413e-04,
       2.51172413e-04, 2.51172413e-04, 3.28667873e-04, 3.28667873e-04,
       3.28667873e-04, 3.28667873e-04, 3.28667873e-04, 5.46538929e-04,
       5.46538929e-04, 5.46538929e-04, 5.46538929e-04, 5.46538929e-04,
       9.51114609e-04, 9.51114609e-04, 9.51114609e-04, 9.51114609e-04,
       9.51114609e-04, 1.63971177e-03, 1.63971177e-03, 1.63971177e-03,
       1.63971177e-03, 1.63971177e-03, 2.59458669e-03, 2.59458669e-03,
      

# future immigration calculation

In [38]:
# Initialize 8x86x27 numpy matrix for future immigration (8 groups, 86 age groups, 27 years from 2024-2050)
future_popu = np.zeros((8, 86, 28))  # from 2023 to 2050
future_immigration = np.zeros((8, 50, 27))

In [34]:
import pandas as pd
immigration_params = pd.read_csv('/Users/haolong/Documents/demos_v_matrix/ckd/data/immigration_params.csv')

In [35]:
immigration_params

,gender,race,agent_age,lower,upper
0,male,chinese,1,0.063372,0.085318
1,male,chinese,2,0.009232,0.033650
2,male,chinese,3,0.006823,0.022721
3,male,chinese,4,0.006257,0.016962
4,male,chinese,5,0.002830,0.013222
...,...,...,...,...,...
395,female,other,46,0.000000,0.016570
396,female,other,47,0.000000,0.020227
397,female,other,48,0.000000,0.000043
398,female,other,49,0.000000,0.011914


In [36]:
# Convert immigration_params (400x5) to 8x50x2 numpy array
# Order: chinese male, chinese female, malay male, malay female, indian male, indian female, other male, other female
uniform_params = np.zeros((8, 50, 2))

races = ['chinese', 'malay', 'indian', 'other']
genders = ['male', 'female']

for race_idx, race in enumerate(races):
    for gender_idx, gender in enumerate(genders):
        group_idx = race_idx * 2 + gender_idx
        mask = (immigration_params['race'] == race) & (immigration_params['gender'] == gender)
        filtered_data = immigration_params[mask]
        
        # Extract lower and upper bounds for ages 1-50
        uniform_params[group_idx, :, 0] = filtered_data['lower'].values  # lower bounds
        uniform_params[group_idx, :, 1] = filtered_data['upper'].values  # upper bounds

uniform_params

array([[[6.33723500e-02, 8.53184700e-02],
        [9.23225800e-03, 3.36497840e-02],
        [6.82251670e-03, 2.27208600e-02],
        [6.25747200e-03, 1.69620200e-02],
        [2.82956330e-03, 1.32224030e-02],
        [2.64508440e-03, 1.42876090e-02],
        [1.22183080e-03, 9.28958000e-03],
        [1.26626580e-03, 7.10042430e-03],
        [8.57784530e-04, 6.45115740e-03],
        [2.76387580e-04, 3.70642360e-03],
        [0.00000000e+00, 3.90528420e-03],
        [0.00000000e+00, 4.56718080e-03],
        [0.00000000e+00, 3.93170000e-03],
        [0.00000000e+00, 2.85633960e-03],
        [0.00000000e+00, 6.76170600e-03],
        [0.00000000e+00, 2.75212530e-03],
        [0.00000000e+00, 2.93802520e-03],
        [0.00000000e+00, 3.92976400e-03],
        [0.00000000e+00, 3.20515530e-03],
        [0.00000000e+00, 7.27510900e-04],
        [0.00000000e+00, 1.13583520e-03],
        [0.00000000e+00, 7.00756600e-03],
        [1.62261130e-03, 1.91137590e-02],
        [9.33435200e-03, 2.8611831

In [46]:
ages = np.arange(0, 85)
fertility_ages = range(15, 50)
for i in [1,0,3,2,5,4,7,6]: # deal with female first, then male 
    # get 2023 population
    popu_2023 = scaled_popu[i][:,-1] # last column
    future_popu[i,:,0] = popu_2023
    ## print(np.sum(immigration_rates[i], axis=0))

    for j in range(1,28): # 2024 to 2050

        immi_rate = np.array([
            np.random.uniform(low, high) 
            for low, high in uniform_params[i]
        ])

        
        # for the other ages (2, 18, 27)
        
        is_female = i % 2  # 1 is female, 0 is male
        year_index = j-1 # index 0 is year 2024
        # this is for mortality rate of 1 - 84
        mortaility_rates = mortality_forecast_from_24[is_female, ages // 5, j-1] / 1000.
        
        # age 0 - 84 --> 1 -- （85）, then experience death this year
        future_popu[i,1:86,j]=  (future_popu[i,0:85,j-1] * (1- mortaility_rates)).astype(int)

        # for 85 and 85+, add those people are still alive 
        mortaility_rate = mortality_forecast_from_24[is_female, 85 // 5, j-1] / 1000.
        future_popu[i,85,j] = (future_popu[i,85,j-1] * (1-mortaility_rate)).astype(int) +  future_popu[i,85,j]

        # then calculate immigration people
        
        future_immigration[i,:,j-1] = (future_popu[i,1:51,j] * immi_rate).astype(int)

        print("i =", i, "is_female =", is_female, 
                "sum immigration =", np.sum(future_immigration[i,:,j-1]))
        # add immigration back 
        future_popu[i,1:51,j] += future_immigration[i,:,j-1]

        # deal wtih fertility
        if i % 2 == 1:
            year = 2023 + j
            rates = [map_fertility_rate(i // 2, year, age, fertility_matrix) for age in fertility_ages]

            births = future_popu[i,15:50,j] * rates
            boys = (births * 1/ (1+ 1.06) ).astype(int)
            girls = (births - boys).astype(int)
            future_popu[i,0,j] =  np.sum(girls)
            future_popu[i-1,0,j] = np.sum(boys)

            # use the gender ratio to determine boys and girls

        


i = 1 is_female = 1 sum immigration = 378.0
i = 1 is_female = 1 sum immigration = 350.0
i = 1 is_female = 1 sum immigration = 354.0
i = 1 is_female = 1 sum immigration = 353.0
i = 1 is_female = 1 sum immigration = 349.0
i = 1 is_female = 1 sum immigration = 300.0
i = 1 is_female = 1 sum immigration = 345.0
i = 1 is_female = 1 sum immigration = 344.0
i = 1 is_female = 1 sum immigration = 331.0
i = 1 is_female = 1 sum immigration = 314.0
i = 1 is_female = 1 sum immigration = 312.0
i = 1 is_female = 1 sum immigration = 305.0
i = 1 is_female = 1 sum immigration = 269.0
i = 1 is_female = 1 sum immigration = 308.0
i = 1 is_female = 1 sum immigration = 294.0
i = 1 is_female = 1 sum immigration = 303.0
i = 1 is_female = 1 sum immigration = 255.0
i = 1 is_female = 1 sum immigration = 263.0
i = 1 is_female = 1 sum immigration = 303.0
i = 1 is_female = 1 sum immigration = 281.0
i = 1 is_female = 1 sum immigration = 303.0
i = 1 is_female = 1 sum immigration = 255.0
i = 1 is_female = 1 sum immigrat

In [47]:
for i in range(8):
    print(future_immigration[i].sum(axis=0))

[267. 191. 272. 248. 213. 237. 206. 230. 206. 213. 221. 191. 175. 216.
 205. 189. 162. 176. 181. 179. 145. 165. 149. 153. 144. 151. 135.]
[378. 350. 354. 353. 349. 300. 345. 344. 331. 314. 312. 305. 269. 308.
 294. 303. 255. 263. 303. 281. 303. 255. 229. 253. 226. 258. 227.]
[6. 4. 4. 4. 4. 3. 3. 3. 5. 3. 3. 3. 3. 2. 2. 3. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2.]
[10.  9.  8.  6.  9.  9.  6.  6.  4.  6.  4.  4.  4.  4.  4.  3.  4.  3.
  2.  3.  3.  2.  2.  3.  2.  2.  3.]
[67. 64. 51. 56. 55. 63. 51. 63. 50. 50. 53. 56. 64. 54. 50. 58. 47. 41.
 48. 48. 50. 32. 27. 46. 28. 20. 32.]
[43. 47. 45. 50. 43. 54. 48. 45. 45. 42. 50. 36. 46. 35. 40. 46. 30. 38.
 40. 33. 34. 24. 29. 32. 20. 20. 20.]
[25. 29. 25. 17. 24. 28. 23. 30. 16. 19. 14. 20. 16. 15. 18. 22. 16. 17.
 12. 13. 14. 13.  9.  9.  7.  7.  4.]
[37. 50. 53. 45. 48. 48. 34. 57. 36. 47. 35. 41. 39. 41. 35. 43. 41. 24.
 27. 35. 29. 27. 28. 21. 27. 24. 32.]


In [43]:
# check malay immigration
future_immigration[3].sum(axis=0)

array([ 7., 10.,  6., 10.,  6.,  7.,  9.,  5.,  6.,  6.,  5.,  5.,  3.,
        3.,  3.,  2.,  5.,  4.,  3.,  3.,  3.,  2.,  3.,  4.,  3.,  4.,
        2.])

In [ ]:
import numpy as np
# Save future_immigration to binary file
future_immigration = future_immigration.astype(np.int32)
with open('../data/migration/future_immigration.bin', 'wb') as f:
    future_immigration.tofile(f)



In [ ]:


# Read back from binary file
#future_immigration = np.zeros((8, 50, 27))

with open('../data/migration/future_immigration.bin', 'rb') as f:
    future_immigration_read = np.fromfile(f, dtype=np.int32).reshape(future_immigration.shape)

future_immigration_read



array([[[33, 41, 36, ..., 22, 25, 18],
        [11,  8, 13, ...,  3,  7,  5],
        [ 6, 12,  8, ...,  2,  6,  5],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0]],

       [[32, 52, 39, ..., 20, 23, 19],
        [ 5, 19,  9, ...,  7,  6,  9],
        [ 4, 12, 10, ...,  3,  4,  3],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  1,  0, ...,  0,  0,  0],
        [ 1,  1,  1, ...,  1,  1,  1]],

       [[ 5,  5,  3, ...,  3,  2,  3],
        [ 1,  1,  1, ...,  0,  0,  0],
        [ 1,  1,  1, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0]],

       ...,

       [[ 8, 16, 14, ..., 11, 11,  9],
        [ 5,  4,  7, ...,  5,  3,  4],
        [ 5,  1,  4, ...,  6,  7,  4],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 1,  1,  1, ...,  0,  0,  1],
        [ 2,  2,  2, ...,  1,  1

In [ ]:
future_immigration_read[7]

array([[ 3, 19, 12, ..., 56, 28, 58],
       [ 2,  2,  2, ..., 11,  9,  5],
       [ 2,  1,  0, ..., 10, 11, 16],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  2, ...,  1,  1,  1],
       [ 2,  1,  2, ...,  1,  1,  1]], dtype=int32)

In [ ]:
# Calculate column sum for future_immigration_read[7]
column_sum = np.sum(future_immigration_read[1], axis=0)
column_sum

array([394, 455, 428, 371, 398, 408, 401, 378, 358, 356, 381, 360, 376,
       364, 362, 328, 341, 365, 333, 329, 330, 257, 333, 274, 305, 255,
       292])

In [ ]:
# Calculate column sum for future_immigration_read[7]
column_sum = np.sum(future_immigration_read[3], axis=0)
column_sum

array([42, 46, 50, 48, 53, 48, 55, 44, 56, 58, 62, 60, 58, 54, 50, 47, 57,
       59, 40, 41, 45, 48, 38, 45, 33, 42, 44])

In [ ]:
# Calculate column sum for future_immigration_read[7]
column_sum = np.sum(future_immigration_read[5], axis=0)
column_sum

array([135, 115, 128, 130, 118, 135, 134, 111, 117, 119, 111,  96, 117,
       104, 120, 108, 114, 117, 100, 119, 119, 120, 125, 118, 117, 115,
       119])

In [ ]:
# Calculate column sum for future_immigration_read[7]
column_sum = np.sum(future_immigration_read[7], axis=0)
column_sum


array([139, 143, 128, 159, 176, 189, 161, 208, 195, 186, 230, 220, 246,
       306, 281, 282, 316, 331, 382, 363, 393, 407, 430, 525, 479, 546,
       613])

In [48]:
# 补救,不知道为什么 immigration的顺序是错的


# # Assign immigration data for first two genders (indices 0 and 1)
# future_immigration[0:2,:,:] = future_immigration_read[0:2,:,:]

# future_immigration[2:4,:,:] = future_immigration_read[6:8,:,:]

# future_immigration[4:6,:,:] = future_immigration_read[4:6,:,:]

# future_immigration[6:8,:,:] = future_immigration_read[2:4,:,:]

future_immigration = future_immigration.astype(np.int32)
with open('../data/migration/future_immigration.bin', 'wb') as f:
    future_immigration.tofile(f)